export const poolData = {
  title: "World Cup Bracket Pool",
  lastUpdated: "2026-07-15",

  scoring: {
    roundOf32: 1,
    roundOf16: 2,
    quarterfinal: 3,
    semifinal: 4,
    final: 5,
    thirdPlace: 3,
  },

  notes: [
    "Otis & Tyler are now scored straight up with the rest of the group.",
    "The Round of 32 is complete.",
    "The Round of 16 is complete.",
    "The quarterfinals are complete.",
    "Spain is through to the final.",
    "The second semifinal is the active match.",
  ],

  matches: [
    { id: "r32-01", round: "Round of 32", points: 1, date: "2026-06-29", fixture: "Germany vs Paraguay", winner: "Paraguay", status: "final" },
    { id: "r32-02", round: "Round of 32", points: 1, date: "2026-06-30", fixture: "France vs Sweden", winner: "France", status: "final" },
    { id: "r32-03", round: "Round of 32", points: 1, date: "2026-06-28", fixture: "South Africa vs Canada", winner: "Canada", status: "final" },
    { id: "r32-04", round: "Round of 32", points: 1, date: "2026-06-29", fixture: "Netherlands vs Morocco", winner: "Morocco", status: "final" },
    { id: "r32-05", round: "Round of 32", points: 1, date: "2026-07-02", fixture: "Portugal vs Croatia", winner: "Portugal", status: "final" },
    { id: "r32-06", round: "Round of 32", points: 1, date: "2026-07-02", fixture: "Spain vs Austria", winner: "Spain", status: "final" },
    { id: "r32-07", round: "Round of 32", points: 1, date: "2026-07-01", fixture: "United States vs Bosnia and Herzegovina", winner: "United States", status: "final" },
    { id: "r32-08", round: "Round of 32", points: 1, date: "2026-07-01", fixture: "Belgium vs Senegal", winner: "Belgium", status: "final" },
    { id: "r32-09", round: "Round of 32", points: 1, date: "2026-06-29", fixture: "Brazil vs Japan", winner: "Brazil", status: "final" },
    { id: "r32-10", round: "Round of 32", points: 1, date: "2026-06-30", fixture: "Ivory Coast vs Norway", winner: "Norway", status: "final" },
    { id: "r32-11", round: "Round of 32", points: 1, date: "2026-06-30", fixture: "Mexico vs Ecuador", winner: "Mexico", status: "final" },
    { id: "r32-12", round: "Round of 32", points: 1, date: "2026-07-01", fixture: "England vs DR Congo", winner: "England", status: "final" },
    { id: "r32-13", round: "Round of 32", points: 1, date: "2026-07-03", fixture: "Argentina vs Cape Verde", winner: "Argentina", status: "final" },
    { id: "r32-14", round: "Round of 32", points: 1, date: "2026-07-03", fixture: "Australia vs Egypt", winner: "Egypt", status: "final" },
    { id: "r32-15", round: "Round of 32", points: 1, date: "2026-07-02", fixture: "Switzerland vs Algeria", winner: "Switzerland", status: "final" },
    { id: "r32-16", round: "Round of 32", points: 1, date: "2026-07-03", fixture: "Colombia vs Ghana", winner: "Colombia", status: "final" },
  ],

  laterRoundMatches: [
    { id: "match-89", roundKey: "roundOf16", round: "Round of 16", fixture: "Paraguay vs France", points: 2, winner: "France" },
    { id: "match-90", roundKey: "roundOf16", round: "Round of 16", fixture: "Canada vs Morocco", points: 2, winner: "Morocco" },
    { id: "match-93", roundKey: "roundOf16", round: "Round of 16", fixture: "Portugal vs Spain", points: 2, winner: "Spain" },
    { id: "match-94", roundKey: "roundOf16", round: "Round of 16", fixture: "United States vs Belgium", points: 2, winner: "Belgium" },
    { id: "match-91", roundKey: "roundOf16", round: "Round of 16", fixture: "Brazil vs Norway", points: 2, winner: "Norway" },
    { id: "match-92", roundKey: "roundOf16", round: "Round of 16", fixture: "Mexico vs England", points: 2, winner: "England" },
    { id: "match-95", roundKey: "roundOf16", round: "Round of 16", fixture: "Argentina vs Egypt", points: 2, winner: "Argentina" },
    { id: "match-96", roundKey: "roundOf16", round: "Round of 16", fixture: "Switzerland vs Colombia", points: 2, winner: "Switzerland" },
    { id: "match-97", roundKey: "quarterfinals", round: "Quarterfinals", fixture: "France vs Morocco", points: 3, winner: "France", score: "France 2–0 Morocco" },
    { id: "match-98", roundKey: "quarterfinals", round: "Quarterfinals", fixture: "Spain vs Belgium", points: 3, winner: "Spain", score: "Spain 2–1 Belgium" },
    { id: "match-99", roundKey: "quarterfinals", round: "Quarterfinals", fixture: "Norway vs England", points: 3, winner: "England", score: "England 2–1 Norway (AET)" },
    { id: "match-100", roundKey: "quarterfinals", round: "Quarterfinals", fixture: "Argentina vs Switzerland", points: 3, winner: "Argentina", score: "Argentina 3–1 Switzerland" },
    { id: "match-101", roundKey: "semifinals", round: "Semifinals", fixture: "France vs Spain", points: 4, winner: "Spain", score: "Spain 2–0 France" },
    { id: "match-102", roundKey: "semifinals", round: "Semifinals", fixture: "England vs Argentina", points: 4, winner: null },
    { id: "match-103", roundKey: "thirdPlace", round: "Third Place", fixture: "France vs Semifinal 102 runner-up", points: 3, winner: null },
    { id: "match-104", roundKey: "final", round: "Final", fixture: "Spain vs Semifinal 102 winner", points: 5, winner: null },
  ],

  laterRoundPicks: {
    John: {
      roundOf16: { "match-89": "France", "match-90": "Netherlands", "match-93": "Spain", "match-94": "United States", "match-91": "Norway", "match-92": "England", "match-95": "Argentina", "match-96": "Colombia" },
      quarterfinals: { "match-97": "France", "match-98": "United States", "match-99": "England", "match-100": "Colombia" },
      semifinals: { "match-101": "France", "match-102": "England" },
      final: { "match-104": "France", runnerUp: "England", champion: "France" },
      thirdPlace: { "match-103": "United States", runnerUp: "Colombia" },
    },
    Henry: {
      roundOf16: { "match-89": "France", "match-90": "Morocco", "match-93": "Spain", "match-94": "United States", "match-91": "Brazil", "match-92": "England", "match-95": "Argentina", "match-96": "Colombia" },
      quarterfinals: { "match-97": "France", "match-98": "Spain", "match-99": "England", "match-100": "Argentina" },
      semifinals: { "match-101": "France", "match-102": "Argentina" },
      final: { "match-104": "France", runnerUp: "Argentina", champion: "France" },
      thirdPlace: { "match-103": "Spain", runnerUp: "England" },
    },
    Louisa: {
      roundOf16: { "match-89": "France", "match-90": "Morocco", "match-93": "Portugal", "match-94": "United States", "match-91": "Brazil", "match-92": "England", "match-95": "Argentina", "match-96": "Colombia" },
      quarterfinals: { "match-97": "France", "match-98": "Portugal", "match-99": "Brazil", "match-100": "Colombia" },
      semifinals: { "match-101": "France", "match-102": "Brazil" },
      final: { "match-104": "France", runnerUp: "Brazil", champion: "France" },
      thirdPlace: { "match-103": null, runnerUp: null, note: "Not clearly visible on Louisa's image" },
    },
    Lawrence: {
      roundOf16: { "match-89": "France", "match-90": "Netherlands", "match-93": "Spain", "match-94": "Belgium", "match-91": "Japan", "match-92": "Mexico", "match-95": "Argentina", "match-96": "Colombia" },
      quarterfinals: { "match-97": "France", "match-98": "Spain", "match-99": "Mexico", "match-100": "Argentina" },
      semifinals: { "match-101": "France", "match-102": "Argentina" },
      final: { "match-104": "France", runnerUp: "Argentina", champion: "France" },
      thirdPlace: { "match-103": "Spain", runnerUp: "Mexico" },
    },
    Julie: {
      roundOf16: { "match-89": "France", "match-90": "Netherlands", "match-93": "Spain", "match-94": "United States", "match-91": "Norway", "match-92": "England", "match-95": "Argentina", "match-96": "Colombia" },
      quarterfinals: { "match-97": "France", "match-98": "Spain", "match-99": "England", "match-100": "Argentina" },
      semifinals: { "match-101": "France", "match-102": "Argentina" },
      final: { "match-104": "France", runnerUp: "Argentina", champion: "France" },
      thirdPlace: { "match-103": "England", runnerUp: "Spain" },
    },
    "Otis & Tyler": {
      roundOf16: { "match-89": "France", "match-90": "Netherlands", "match-93": "Croatia", "match-94": "Senegal", "match-91": "Brazil", "match-92": "England", "match-95": "Argentina", "match-96": "Colombia" },
      quarterfinals: { "match-97": "France", "match-98": "Croatia", "match-99": "England", "match-100": "Argentina" },
      semifinals: { "match-101": "France", "match-102": "Argentina" },
      final: { "match-104": "France", runnerUp: "Argentina", champion: "France" },
      thirdPlace: { "match-103": "England", runnerUp: "Croatia" },
    },
  },

  players: [
    {
      name: "Henry",
      champion: "France",
      finalist: "Argentina",
      roundOf32Picks: ["Germany", "France", "Canada", "Morocco", "Portugal", "Spain", "United States", "Belgium", "Brazil", "Norway", "Mexico", "England", "Argentina", "Egypt", "Switzerland", "Colombia"],
    },
    {
      name: "Louisa",
      champion: "France",
      finalist: "Brazil",
      roundOf32Picks: ["Germany", "France", "Canada", "Morocco", "Portugal", "Spain", "United States", "Belgium", "Brazil", "Norway", "Mexico", "England", "Argentina", "Egypt", "Algeria", "Colombia"],
    },
    {
      name: "Lawrence",
      champion: "France",
      finalist: "Argentina",
      roundOf32Picks: ["Germany", "France", "Canada", "Netherlands", "Portugal", "Spain", "United States", "Belgium", "Japan", "Norway", "Mexico", "England", "Argentina", "Egypt", "Switzerland", "Colombia"],
    },
    {
      name: "Julie",
      champion: "France",
      finalist: "Argentina",
      roundOf32Picks: ["Germany", "France", "Canada", "Netherlands", "Croatia", "Spain", "United States", "Belgium", "Brazil", "Norway", "Mexico", "England", "Argentina", "Australia", "Switzerland", "Colombia"],
    },
    {
      name: "Otis & Tyler",
      champion: "France",
      finalist: "Argentina",
      roundOf32Picks: ["Germany", "France", "Canada", "Netherlands", "Croatia", "Spain", "United States", "Senegal", "Brazil", "Norway", "Mexico", "England", "Argentina", "Egypt", "Algeria", "Colombia"],
    },
    {
      name: "John",
      champion: "France",
      finalist: "England",
      roundOf32Picks: ["Germany", "France", "South Africa", "Netherlands", "Portugal", "Spain", "United States", "Senegal", "Japan", "Norway", "Ecuador", "England", "Argentina", "Egypt", "Switzerland", "Colombia"],
    },
  ],
};
